### ISSUE TITLE
Issues with `**kwargs`

### ISSUE THREAD

**Issue by wch** [machow/quartodoc#93]
This is related to #91. There are the same three issues.

For example, for the `row` function (https://github.com/rstudio/py-shiny/blob/d036a8aaa/shiny/ui/_bootstrap.py#L42-L60):

1. The function signature should show `**kwargs`, not `kwargs`.
2. The default is not `{}`.
3. Quartodoc should print some sort of message when the docstring has `kwargs` instead of `**kwargs`. 

<img width="791" alt="image" src="https://user-images.githubusercontent.com/86978/231247767-63a19509-b016-4053-8bfe-5e401481f58e.png">

**Comment by machow** [comment]
Ah, sorry--this bug should be fixed in the above PR.

The default for `*args` and `**kwargs` is an empty tuple and a dictionary, respectively -- since that is what their value is if these arguments are unspecified (e.g. if `def f(**kwargs): ...` is called as `f()`, then `**kwargs` is an empty dictionary.

Can you say more about this piece?

> Quartodoc should print some sort of message when the docstring has kwargs

Are you saying it should print a message anytime it thinks it's about to render a signature with an argument named `kwargs`, that does not have a two stars in front of it? What would the goal be?

**Comment by wch** [comment]
I installed the latest (`quartodoc-0.2.2.dev9+g6814040`) and see no changes in the resulting .qmd. The three issues are still present.

>> Quartodoc should print some sort of message when the docstring has `kwargs`

> Are you saying it should print a message anytime it thinks it's about to render a signature with an argument named `kwargs`, that does not have a two stars in front of it? What would the goal be?

Yes, it should print a warning or error if the following are both true:
- There is a parameter in the function with `**`. The specific name of the parameter doesn't matter. It could be `def f(**extra_args): ...`.
- There is a parameter that is not an exact match. For example, suppose the docstring has `extra_args` instead of `**extra_args`. This should be an error.

This would enforce consistency in the documentation so that it's not `kwargs` in some docstrings and `**kwargs` in others. The numpydoc style guide says to use `**kwargs`, which makes sense to me: https://numpydoc.readthedocs.io/en/latest/format.html#parameters

****

As for displaying `{}` as the default value `**kwargs`: One might make the argument on technical grounds that the default is `{}`, but that's technically incorrect, and also confusing for users.

It is technically incorrect because when a Python function uses `{}` as a default value, that is a _mutable object_ whose state can carry over to future calls to the function, but that's not what happens with `**kwargs`. For example, here's a function that uses `{}` as a default:

```py
def f(x={}):
    return x

y = f()
y["a"] = 1

z = f()
z
#> {'a': 1}
```

But with `**kwargs`, that's not what happens:
```py
def g(**kwargs):
    return kwargs

y = g()
y["a"] = 1

z = g()
z
#> {}
```

It's confusing for users because from the perspective of the person calling the function, they don't interact with the dictionary. They care about what they can put into it, not the data structure that it's wrapped into on the inside of the function.

**Comment by machow** [comment]
> This would enforce consistency in the documentation so that it's not kwargs in some docstrings and **kwargs in others. The numpydoc style guide says to use **kwargs, which makes sense to me

Quartodoc provides a docstring renderer. If you want to request changes to the parsing and validation of docstrings, please open an issue on [griffe](https://github.com/mkdocstrings/griffe/issues). AFAIK, numpydoc does not validate this. We could get more into validation at some point in the future, but it feels a bit early to have opinions there.

> As for displaying {} as the default value **kwarg

I'm going to close this issue, and open one on whether the default for `**kwargs` should be shown as `{}`. 

> It is technically incorrect because when a Python function uses {} as a default value, that is a mutable object whose state can carry over to future calls to the function, but that's not what happens with **kwargs.

I don't think you can argue the technical correctness of `**kwargs` and `*args` defaults, based on the behavior of regular parameter defaults. `**kwargs` and `*args` are their own kinds of parameters (e.g. in the AST representation), governed by their own set of behaviors. (but point taken putting anything in their defaults is sort of overkill 😬)

**Comment by machow** [comment]
I'm going to close, so #112 can track the remaining issue (definitely let me know if I missed something in terms of validation)
